language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

install:
  - pip install --upgrade pip setuptools wheel
  - sudo apt-get install python-numpy python-scipy gfortran
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - pytest

after_success: pip install codecov && codecov
